In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sqlite3
from datetime import datetime

%matplotlib inline
er='https://rate.bot.com.tw/xrt'

In [8]:
table = pd.read_html(er)[0]

table = table.drop(table.columns[5:12],axis=1)
table = table.drop(table.columns[5],axis=1)

In [113]:
table

                        幣別              現金匯率 Unnamed: 3_level_0    即期匯率
        Unnamed: 0_level_1     本行買入     本行賣出               本行買入    本行賣出
0       美金 (USD)  美金 (USD)    30.35    31.04              30.72   30.82
1       港幣 (HKD)  港幣 (HKD)    3.761    3.977              3.897   3.957
2       英鎊 (GBP)  英鎊 (GBP)    39.01    41.13              40.01   40.43
3       澳幣 (AUD)  澳幣 (AUD)    21.84    22.62              22.11   22.34
4   加拿大幣 (CAD)  加拿大幣 (CAD)    22.97    23.88              23.36   23.58
5   新加坡幣 (SGD)  新加坡幣 (SGD)    21.81    22.72               22.3   22.48
6   瑞士法郎 (CHF)  瑞士法郎 (CHF)    29.83    31.03              30.49   30.78
7       日圓 (JPY)  日圓 (JPY)   0.2622    0.275             0.2695  0.2735
8     南非幣 (ZAR)  南非幣 (ZAR)        -        -               2.13    2.21
9     瑞典幣 (SEK)  瑞典幣 (SEK)     3.02     3.54               3.36    3.46
10      紐元 (NZD)  紐元 (NZD)    20.03    20.88              20.41   20.61
11      泰幣 (THB)  泰幣 (THB)   0.8096   0.9976             0.9182  0.9582
12  菲國比索 (PHP)  菲國比索 (PHP)   0.5063   0.6393                  -       -
13    印尼幣 (IDR)  印尼幣 (IDR)  0.00173  0.00243                  -       -
14      歐元 (EUR)  歐元 (EUR)     34.3    35.64              34.92   35.32
15      韓元 (KRW)  韓元 (KRW)  0.02563  0.02953                  -       -
16    越南盾 (VND)  越南盾 (VND)  0.00095  0.00145                  -       -
17    馬來幣 (MYR)  馬來幣 (MYR)    6.277    7.907                  -       -
18    人民幣 (CNY)  人民幣 (CNY)    4.349    4.511              4.421   4.471

In [9]:
#重新命名欄位名稱
table.columns = [u'幣別', u'現金_買入', u'現金_賣出', u'即期_買入', u'即期_賣出']
table

                        幣別    現金_買入    現金_賣出   即期_買入   即期_賣出
0       美金 (USD)  美金 (USD)    30.35    31.04   30.72   30.82
1       港幣 (HKD)  港幣 (HKD)    3.761    3.977   3.897   3.957
2       英鎊 (GBP)  英鎊 (GBP)    39.03    41.15   40.03   40.45
3       澳幣 (AUD)  澳幣 (AUD)    21.84    22.62   22.11   22.34
4   加拿大幣 (CAD)  加拿大幣 (CAD)    22.97    23.88   23.36   23.58
5   新加坡幣 (SGD)  新加坡幣 (SGD)    21.81    22.72    22.3   22.48
6   瑞士法郎 (CHF)  瑞士法郎 (CHF)    29.84    31.04    30.5   30.79
7       日圓 (JPY)  日圓 (JPY)   0.2623   0.2751  0.2696  0.2736
8     南非幣 (ZAR)  南非幣 (ZAR)        -        -    2.12     2.2
9     瑞典幣 (SEK)  瑞典幣 (SEK)     3.01     3.53    3.35    3.45
10      紐元 (NZD)  紐元 (NZD)    20.03    20.88   20.41   20.61
11      泰幣 (THB)  泰幣 (THB)   0.8099   0.9979  0.9185  0.9585
12  菲國比索 (PHP)  菲國比索 (PHP)   0.5066   0.6396       -       -
13    印尼幣 (IDR)  印尼幣 (IDR)  0.00173  0.00243       -       -
14      歐元 (EUR)  歐元 (EUR)     34.3    35.64   34.92   35.32
15      韓元 (KRW)  韓元 (KRW)  0.02564  0.02954       -       -
16    越南盾 (VND)  越南盾 (VND)  0.00095  0.00145       -       -
17    馬來幣 (MYR)  馬來幣 (MYR)    6.277    7.907       -       -
18    人民幣 (CNY)  人民幣 (CNY)    4.349    4.511   4.421   4.471

In [10]:
table[u'幣別'] = table[u'幣別'].str.extract('\((\w+)\)') #幣別值有重複字 利用正規式取英文代號 ('(\w+)') 為以中文取代

In [11]:
table

     幣別    現金_買入    現金_賣出   即期_買入   即期_賣出
0   USD    30.35    31.04   30.72   30.82
1   HKD    3.761    3.977   3.897   3.957
2   GBP    39.03    41.15   40.03   40.45
3   AUD    21.84    22.62   22.11   22.34
4   CAD    22.97    23.88   23.36   23.58
5   SGD    21.81    22.72    22.3   22.48
6   CHF    29.84    31.04    30.5   30.79
7   JPY   0.2623   0.2751  0.2696  0.2736
8   ZAR        -        -    2.12     2.2
9   SEK     3.01     3.53    3.35    3.45
10  NZD    20.03    20.88   20.41   20.61
11  THB   0.8099   0.9979  0.9185  0.9585
12  PHP   0.5066   0.6396       -       -
13  IDR  0.00173  0.00243       -       -
14  EUR     34.3    35.64   34.92   35.32
15  KRW  0.02564  0.02954       -       -
16  VND  0.00095  0.00145       -       -
17  MYR    6.277    7.907       -       -
18  CNY    4.349    4.511   4.421   4.471

In [14]:
#將資料存到Sqlite

#新增日期欄位&使用今天的日期
table['Date'] = datetime.now().strftime('%Y-%m-%d')
#檢查格式
table.info()

     幣別    現金_買入    現金_賣出   即期_買入   即期_賣出        Date
0   USD    30.35    31.04   30.72   30.82  2018-11-06
1   HKD    3.761    3.977   3.897   3.957  2018-11-06
2   GBP    39.03    41.15   40.03   40.45  2018-11-06
3   AUD    21.84    22.62   22.11   22.34  2018-11-06
4   CAD    22.97    23.88   23.36   23.58  2018-11-06
5   SGD    21.81    22.72    22.3   22.48  2018-11-06
6   CHF    29.84    31.04    30.5   30.79  2018-11-06
7   JPY   0.2623   0.2751  0.2696  0.2736  2018-11-06
8   ZAR        -        -    2.12     2.2  2018-11-06
9   SEK     3.01     3.53    3.35    3.45  2018-11-06
10  NZD    20.03    20.88   20.41   20.61  2018-11-06
11  THB   0.8099   0.9979  0.9185  0.9585  2018-11-06
12  PHP   0.5066   0.6396       -       -  2018-11-06
13  IDR  0.00173  0.00243       -       -  2018-11-06
14  EUR     34.3    35.64   34.92   35.32  2018-11-06
15  KRW  0.02564  0.02954       -       -  2018-11-06
16  VND  0.00095  0.00145       -       -  2018-11-06
17  MYR    6.277    7.907       -       -  2018-11-06
18  CNY    4.349    4.511   4.421   4.471  2018-11-06

In [16]:
#將date轉成pandas日期資料型式
table['Date']=pd.to_datetime(table['Date'])
table

     幣別    現金_買入    現金_賣出   即期_買入   即期_賣出       Date
0   USD    30.35    31.04   30.72   30.82 2018-11-06
1   HKD    3.761    3.977   3.897   3.957 2018-11-06
2   GBP    39.03    41.15   40.03   40.45 2018-11-06
3   AUD    21.84    22.62   22.11   22.34 2018-11-06
4   CAD    22.97    23.88   23.36   23.58 2018-11-06
5   SGD    21.81    22.72    22.3   22.48 2018-11-06
6   CHF    29.84    31.04    30.5   30.79 2018-11-06
7   JPY   0.2623   0.2751  0.2696  0.2736 2018-11-06
8   ZAR        -        -    2.12     2.2 2018-11-06
9   SEK     3.01     3.53    3.35    3.45 2018-11-06
10  NZD    20.03    20.88   20.41   20.61 2018-11-06
11  THB   0.8099   0.9979  0.9185  0.9585 2018-11-06
12  PHP   0.5066   0.6396       -       - 2018-11-06
13  IDR  0.00173  0.00243       -       - 2018-11-06
14  EUR     34.3    35.64   34.92   35.32 2018-11-06
15  KRW  0.02564  0.02954       -       - 2018-11-06
16  VND  0.00095  0.00145       -       - 2018-11-06
17  MYR    6.277    7.907       -       - 2018-11-06
18  CNY    4.349    4.511   4.421   4.471 2018-11-06

In [17]:
#存檔 以
with sqlite3.connect('currency.sqlite') as db:
    table.to_sql('currency',con=db,if_exists='append')

In [18]:
with sqlite3.connect('currency.sqlite') as db:
    df=pd.read_sql_query('select * from currency', con=db)
df

    index   幣別    現金_買入    現金_賣出   即期_買入   即期_賣出                 Date
0       0  USD    30.35    31.04   30.72   30.82  2018-11-06 00:00:00
1       1  HKD    3.761    3.977   3.897   3.957  2018-11-06 00:00:00
2       2  GBP    39.03    41.15   40.03   40.45  2018-11-06 00:00:00
3       3  AUD    21.84    22.62   22.11   22.34  2018-11-06 00:00:00
4       4  CAD    22.97    23.88   23.36   23.58  2018-11-06 00:00:00
5       5  SGD    21.81    22.72    22.3   22.48  2018-11-06 00:00:00
6       6  CHF    29.84    31.04    30.5   30.79  2018-11-06 00:00:00
7       7  JPY   0.2623   0.2751  0.2696  0.2736  2018-11-06 00:00:00
8       8  ZAR        -        -    2.12     2.2  2018-11-06 00:00:00
9       9  SEK     3.01     3.53    3.35    3.45  2018-11-06 00:00:00
10     10  NZD    20.03    20.88   20.41   20.61  2018-11-06 00:00:00
11     11  THB   0.8099   0.9979  0.9185  0.9585  2018-11-06 00:00:00
12     12  PHP   0.5066   0.6396       -       -  2018-11-06 00:00:00
13     13  IDR  0.00173  0.00243       -       -  2018-11-06 00:00:00
14     14  EUR     34.3    35.64   34.92   35.32  2018-11-06 00:00:00
15     15  KRW  0.02564  0.02954       -       -  2018-11-06 00:00:00
16     16  VND  0.00095  0.00145       -       -  2018-11-06 00:00:00
17     17  MYR    6.277    7.907       -       -  2018-11-06 00:00:00
18     18  CNY    4.349    4.511   4.421   4.471  2018-11-06 00:00:00